import { RealtimeAction, EventScopeType } from './eventEnvelope';

export enum AcadexEventType {
  // Notification Events
  NOTIFICATION_CREATED = 'notification.created',
  NOTIFICATION_UPDATED = 'notification.updated',
  NOTIFICATION_READ = 'notification.read',

  // Announcement Events
  ANNOUNCEMENT_CREATED = 'announcement.created',
  ANNOUNCEMENT_UPDATED = 'announcement.updated',
  ANNOUNCEMENT_PUBLISHED = 'announcement.published',
  ANNOUNCEMENT_CANCELLED = 'announcement.cancelled',
  ANNOUNCEMENT_EXPIRED = 'announcement.expired',

  // Request Events
  REQUEST_CREATED = 'request.created',
  REQUEST_SUBMITTED = 'request.submitted',
  REQUEST_UNDER_REVIEW = 'request.underReview',
  REQUEST_APPROVED = 'request.approved',
  REQUEST_REJECTED = 'request.rejected',
  REQUEST_CANCELLED = 'request.cancelled',
  REQUEST_CLOSED = 'request.closed',
  REQUEST_UPDATED = 'request.updated',
  REQUEST_STATUS_CHANGED = 'request.statusChanged',

  // Faculty Assignment Events
  FACULTY_ASSIGNMENT_CREATED = 'facultyAssignment.created',
  FACULTY_ASSIGNMENT_UPDATED = 'facultyAssignment.updated',
  FACULTY_ASSIGNMENT_ENDED = 'facultyAssignment.ended',

  // Student Enrollment Events
  STUDENT_ENROLLMENT_CREATED = 'studentEnrollment.created',
  STUDENT_ENROLLMENT_UPDATED = 'studentEnrollment.updated',
  STUDENT_ENROLLMENT_ENDED = 'studentEnrollment.ended',

  // Timetable Events
  TIMETABLE_CREATED = 'timetable.created',
  TIMETABLE_UPDATED = 'timetable.updated',
  TIMETABLE_PUBLISHED = 'timetable.published',
  TIMETABLE_UNPUBLISHED = 'timetable.unpublished',
  TIMETABLE_ARCHIVED = 'timetable.archived',

  // Attendance Events
  ATTENDANCE_SESSION_CREATED = 'attendance.sessionCreated',
  ATTENDANCE_SESSION_UPDATED = 'attendance.sessionUpdated',
  ATTENDANCE_LOCKED = 'attendance.locked',
  ATTENDANCE_CLOSED = 'attendance.closed',
  ATTENDANCE_RECORD_BATCH_UPDATED = 'attendance.recordBatchUpdated',

  // Assignment Events
  ASSIGNMENT_CREATED = 'assignment.created',
  ASSIGNMENT_UPDATED = 'assignment.updated',
  ASSIGNMENT_PUBLISHED = 'assignment.published',
  ASSIGNMENT_CLOSED = 'assignment.closed',

  // Submission Events
  SUBMISSION_SUBMITTED = 'submission.submitted',
  SUBMISSION_REVIEWED = 'submission.reviewed',

  // Internal Assessment Events
  ASSESSMENT_CREATED = 'assessment.created',
  ASSESSMENT_UPDATED = 'assessment.updated',
  ASSESSMENT_OPENED = 'assessment.opened',
  ASSESSMENT_CLOSED = 'assessment.closed',
  ASSESSMENT_PUBLISHED = 'assessment.published',
  ASSESSMENT_MARK_CORRECTED = 'assessment.markCorrected',

  // Note Events
  NOTE_CREATED = 'note.created',
  NOTE_UPDATED = 'note.updated',
  NOTE_ARCHIVED = 'note.archived',

  // Practical / Lab Events
  PRACTICAL_SESSION_CREATED = 'practical.sessionCreated',
  PRACTICAL_SESSION_OPENED = 'practical.sessionOpened',
  PRACTICAL_SESSION_UPDATED = 'practical.sessionUpdated',
  PRACTICAL_SESSION_COMPLETED = 'practical.sessionCompleted',
  PRACTICAL_SESSION_CANCELLED = 'practical.sessionCancelled',
  PRACTICAL_PARTICIPATION_UPDATED = 'practical.participationUpdated',

  // Academic Record Events (Prompt 42)
  ACADEMIC_RECORD_CREATED = 'academicRecord.created',
  ACADEMIC_RECORD_UPDATED = 'academicRecord.updated',
  ACADEMIC_RECORD_PROGRESSION_UPDATED = 'academicRecord.progressionUpdated',
  SUBJECT_ACADEMIC_RECORD_UPDATED = 'academicRecord.subjectUpdated',

  // Academic Result Events (Prompt 44)
  ACADEMIC_RESULT_CALCULATED = 'academicResult.calculated',
  ACADEMIC_RESULT_UNDER_REVIEW = 'academicResult.underReview',
  ACADEMIC_RESULT_FINALIZED = 'academicResult.finalized',
  ACADEMIC_RESULT_PUBLISHED = 'academicResult.published',
  ACADEMIC_RESULT_REOPENED = 'academicResult.reopened',

  // Calendar Events (Prompt 45)
  CALENDAR_CREATED = 'calendar.created',
  CALENDAR_UPDATED = 'calendar.updated',
  CALENDAR_EVENT_CREATED = 'calendar.eventCreated',
  CALENDAR_EVENT_UPDATED = 'calendar.eventUpdated',
  CALENDAR_EVENT_CANCELLED = 'calendar.eventCancelled',
  CALENDAR_OVERRIDE_UPDATED = 'calendar.overrideUpdated',

  // Profile Events (Prompt 48)
  PROFILE_UPDATED = 'profile.updated',
  PROFILE_AVATAR_UPDATED = 'profile.avatar.updated',
}

export interface EventDefinition {
  eventType: AcadexEventType;
  aggregateType: string;
  defaultAction: RealtimeAction;
  allowedScopeTypes: EventScopeType[];
  version: number;
  description: string;
  requiredPayloadKeys: string[];
}

export const EVENT_REGISTRY: Record<AcadexEventType, EventDefinition> = {
  [AcadexEventType.NOTIFICATION_CREATED]: {
    eventType: AcadexEventType.NOTIFICATION_CREATED,
    aggregateType: 'Notification',
    defaultAction: 'CREATED',
    allowedScopeTypes: ['user'],
    version: 1,
    description: 'A new persistent notification was created for a specific user',
    requiredPayloadKeys: ['notificationId'],
  },
  [AcadexEventType.NOTIFICATION_UPDATED]: {
    eventType: AcadexEventType.NOTIFICATION_UPDATED,
    aggregateType: 'Notification',
    defaultAction: 'UPDATED',
    allowedScopeTypes: ['user'],
    version: 1,
    description: 'A notification status or contents were updated',
    requiredPayloadKeys: ['notificationId'],
  },
  [AcadexEventType.NOTIFICATION_READ]: {
    eventType: AcadexEventType.NOTIFICATION_READ,
    aggregateType: 'Notification',
    defaultAction: 'READ',
    allowedScopeTypes: ['user'],
    version: 1,
    description: 'Notification or all notifications marked as read',
    requiredPayloadKeys: ['userId'],
  },

  [AcadexEventType.ANNOUNCEMENT_CREATED]: {
    eventType: AcadexEventType.ANNOUNCEMENT_CREATED,
    aggregateType: 'Announcement',
    defaultAction: 'CREATED',
    allowedScopeTypes: ['college', 'department', 'role'],
    version: 1,
    description: 'A new announcement was created as draft or published',
    requiredPayloadKeys: ['announcementId'],
  },
  [AcadexEventType.ANNOUNCEMENT_UPDATED]: {
    eventType: AcadexEventType.ANNOUNCEMENT_UPDATED,
    aggregateType: 'Announcement',
    defaultAction: 'UPDATED',
    allowedScopeTypes: ['college', 'department', 'role'],
    version: 1,
    description: 'An announcement was updated or edited',
    requiredPayloadKeys: ['announcementId'],
  },
  [AcadexEventType.ANNOUNCEMENT_PUBLISHED]: {
    eventType: AcadexEventType.ANNOUNCEMENT_PUBLISHED,
    aggregateType: 'Announcement',
    defaultAction: 'PUBLISHED',
    allowedScopeTypes: ['college', 'department', 'role'],
    version: 1,
    description: 'An announcement was published to target audience',
    requiredPayloadKeys: ['announcementId'],
  },
  [AcadexEventType.ANNOUNCEMENT_CANCELLED]: {
    eventType: AcadexEventType.ANNOUNCEMENT_CANCELLED,
    aggregateType: 'Announcement',
    defaultAction: 'CANCELLED',
    allowedScopeTypes: ['college', 'department', 'role'],
    version: 1,
    description: 'An announcement was cancelled or withdrawn',
    requiredPayloadKeys: ['announcementId'],
  },
  [AcadexEventType.ANNOUNCEMENT_EXPIRED]: {
    eventType: AcadexEventType.ANNOUNCEMENT_EXPIRED,
    aggregateType: 'Announcement',
    defaultAction: 'STATUS_CHANGED',
    allowedScopeTypes: ['college', 'department', 'role'],
    version: 1,
    description: 'An announcement reached its expiry date',
    requiredPayloadKeys: ['announcementId'],
  },

  [AcadexEventType.REQUEST_CREATED]: {
    eventType: AcadexEventType.REQUEST_CREATED,
    aggregateType: 'Request',
    defaultAction: 'CREATED',
    allowedScopeTypes: ['user', 'department', 'role', 'college'],
    version: 1,
    description: 'A request was created',
    requiredPayloadKeys: ['requestId'],
  },
  [AcadexEventType.REQUEST_SUBMITTED]: {
    eventType: AcadexEventType.REQUEST_SUBMITTED,
    aggregateType: 'Request',
    defaultAction: 'SUBMITTED',
    allowedScopeTypes: ['user', 'department', 'role', 'college'],
    version: 1,
    description: 'A request was officially submitted for review',
    requiredPayloadKeys: ['requestId'],
  },
  [AcadexEventType.REQUEST_UNDER_REVIEW]: {
    eventType: AcadexEventType.REQUEST_UNDER_REVIEW,
    aggregateType: 'Request',
    defaultAction: 'STATUS_CHANGED',
    allowedScopeTypes: ['user', 'department', 'role'],
    version: 1,
    description: 'A request was taken under review by an authority',
    requiredPayloadKeys: ['requestId', 'status'],
  },
  [AcadexEventType.REQUEST_APPROVED]: {
    eventType: AcadexEventType.REQUEST_APPROVED,
    aggregateType: 'Request',
    defaultAction: 'STATUS_CHANGED',
    allowedScopeTypes: ['user', 'department', 'role'],
    version: 1,
    description: 'A request was approved by the reviewer',
    requiredPayloadKeys: ['requestId', 'status'],
  },
  [AcadexEventType.REQUEST_REJECTED]: {
    eventType: AcadexEventType.REQUEST_REJECTED,
    aggregateType: 'Request',
    defaultAction: 'STATUS_CHANGED',
    allowedScopeTypes: ['user', 'department', 'role'],
    version: 1,
    description: 'A request was rejected by the reviewer',
    requiredPayloadKeys: ['requestId', 'status'],
  },
  [AcadexEventType.REQUEST_CANCELLED]: {
    eventType: AcadexEventType.REQUEST_CANCELLED,
    aggregateType: 'Request',
    defaultAction: 'STATUS_CHANGED',
    allowedScopeTypes: ['user', 'department', 'role'],
    version: 1,
    description: 'A request was cancelled by the requester or admin',
    requiredPayloadKeys: ['requestId', 'status'],
  },
  [AcadexEventType.REQUEST_CLOSED]: {
    eventType: AcadexEventType.REQUEST_CLOSED,
    aggregateType: 'Request',
    defaultAction: 'STATUS_CHANGED',
    allowedScopeTypes: ['user', 'department', 'role'],
    version: 1,
    description: 'A request was closed',
    requiredPayloadKeys: ['requestId', 'status'],
  },
  [AcadexEventType.REQUEST_UPDATED]: {
    eventType: AcadexEventType.REQUEST_UPDATED,
    aggregateType: 'Request',
    defaultAction: 'UPDATED',
    allowedScopeTypes: ['user', 'department', 'role'],
    version: 1,
    description: 'Request details or status were updated',
    requiredPayloadKeys: ['requestId'],
  },
  [AcadexEventType.REQUEST_STATUS_CHANGED]: {
    eventType: AcadexEventType.REQUEST_STATUS_CHANGED,
    aggregateType: 'Request',
    defaultAction: 'STATUS_CHANGED',
    allowedScopeTypes: ['user', 'department', 'role'],
    version: 1,
    description: 'Request moved to approved, rejected, resolved, etc.',
    requiredPayloadKeys: ['requestId', 'status'],
  },

  [AcadexEventType.FACULTY_ASSIGNMENT_CREATED]: {
    eventType: AcadexEventType.FACULTY_ASSIGNMENT_CREATED,
    aggregateType: 'FacultyAssignment',
    defaultAction: 'CREATED',
    allowedScopeTypes: ['college', 'department', 'user'],
    version: 1,
    description: 'A teaching assignment was created for a faculty member',
    requiredPayloadKeys: ['assignmentId', 'facultyId'],
  },
  [AcadexEventType.FACULTY_ASSIGNMENT_UPDATED]: {
    eventType: AcadexEventType.FACULTY_ASSIGNMENT_UPDATED,
    aggregateType: 'FacultyAssignment',
    defaultAction: 'UPDATED',
    allowedScopeTypes: ['college', 'department', 'user'],
    version: 1,
    description: 'A teaching assignment was updated',
    requiredPayloadKeys: ['assignmentId', 'facultyId'],
  },
  [AcadexEventType.FACULTY_ASSIGNMENT_ENDED]: {
    eventType: AcadexEventType.FACULTY_ASSIGNMENT_ENDED,
    aggregateType: 'FacultyAssignment',
    defaultAction: 'CLOSED',
    allowedScopeTypes: ['college', 'department', 'user'],
    version: 1,
    description: 'A teaching assignment was deactivated or ended',
    requiredPayloadKeys: ['assignmentId', 'facultyId'],
  },

  [AcadexEventType.STUDENT_ENROLLMENT_CREATED]: {
    eventType: AcadexEventType.STUDENT_ENROLLMENT_CREATED,
    aggregateType: 'StudentEnrollment',
    defaultAction: 'CREATED',
    allowedScopeTypes: ['user', 'department', 'channel'],
    version: 1,
    description: 'A student was enrolled into a section / academic structure',
    requiredPayloadKeys: ['enrollmentId', 'studentId'],
  },
  [AcadexEventType.STUDENT_ENROLLMENT_UPDATED]: {
    eventType: AcadexEventType.STUDENT_ENROLLMENT_UPDATED,
    aggregateType: 'StudentEnrollment',
    defaultAction: 'UPDATED',
    allowedScopeTypes: ['user', 'department', 'channel'],
    version: 1,
    description: 'Student enrollment status or placement changed',
    requiredPayloadKeys: ['enrollmentId', 'studentId'],
  },
  [AcadexEventType.STUDENT_ENROLLMENT_ENDED]: {
    eventType: AcadexEventType.STUDENT_ENROLLMENT_ENDED,
    aggregateType: 'StudentEnrollment',
    defaultAction: 'CLOSED',
    allowedScopeTypes: ['user', 'department', 'channel'],
    version: 1,
    description: 'Student enrollment was terminated or transferred',
    requiredPayloadKeys: ['enrollmentId', 'studentId'],
  },

  [AcadexEventType.TIMETABLE_CREATED]: {
    eventType: AcadexEventType.TIMETABLE_CREATED,
    aggregateType: 'Timetable',
    defaultAction: 'CREATED',
    allowedScopeTypes: ['college', 'department', 'channel'],
    version: 1,
    description: 'A timetable schedule entry was created',
    requiredPayloadKeys: ['timetableId'],
  },
  [AcadexEventType.TIMETABLE_UPDATED]: {
    eventType: AcadexEventType.TIMETABLE_UPDATED,
    aggregateType: 'Timetable',
    defaultAction: 'UPDATED',
    allowedScopeTypes: ['college', 'department', 'channel'],
    version: 1,
    description: 'A timetable schedule entry was modified',
    requiredPayloadKeys: ['timetableId'],
  },
  [AcadexEventType.TIMETABLE_PUBLISHED]: {
    eventType: AcadexEventType.TIMETABLE_PUBLISHED,
    aggregateType: 'Timetable',
    defaultAction: 'PUBLISHED',
    allowedScopeTypes: ['college', 'department', 'channel'],
    version: 1,
    description: 'A timetable was published to students and faculty',
    requiredPayloadKeys: ['timetableId'],
  },
  [AcadexEventType.TIMETABLE_UNPUBLISHED]: {
    eventType: AcadexEventType.TIMETABLE_UNPUBLISHED,
    aggregateType: 'Timetable',
    defaultAction: 'UNPUBLISHED',
    allowedScopeTypes: ['college', 'department', 'channel'],
    version: 1,
    description: 'A timetable was unpublished',
    requiredPayloadKeys: ['timetableId'],
  },
  [AcadexEventType.TIMETABLE_ARCHIVED]: {
    eventType: AcadexEventType.TIMETABLE_ARCHIVED,
    aggregateType: 'Timetable',
    defaultAction: 'ARCHIVED',
    allowedScopeTypes: ['college', 'department', 'channel'],
    version: 1,
    description: 'A timetable entry was deleted or archived',
    requiredPayloadKeys: ['timetableId'],
  },

  [AcadexEventType.ATTENDANCE_SESSION_CREATED]: {
    eventType: AcadexEventType.ATTENDANCE_SESSION_CREATED,
    aggregateType: 'AttendanceSession',
    defaultAction: 'CREATED',
    allowedScopeTypes: ['college', 'department', 'user', 'channel'],
    version: 1,
    description: 'An attendance session was opened by faculty',
    requiredPayloadKeys: ['sessionId'],
  },
  [AcadexEventType.ATTENDANCE_SESSION_UPDATED]: {
    eventType: AcadexEventType.ATTENDANCE_SESSION_UPDATED,
    aggregateType: 'AttendanceSession',
    defaultAction: 'UPDATED',
    allowedScopeTypes: ['college', 'department', 'user', 'channel'],
    version: 1,
    description: 'Attendance session state was modified',
    requiredPayloadKeys: ['sessionId'],
  },
  [AcadexEventType.ATTENDANCE_LOCKED]: {
    eventType: AcadexEventType.ATTENDANCE_LOCKED,
    aggregateType: 'AttendanceSession',
    defaultAction: 'LOCKED',
    allowedScopeTypes: ['college', 'department', 'user', 'channel'],
    version: 1,
    description: 'Attendance session was locked against further student modifications',
    requiredPayloadKeys: ['sessionId'],
  },
  [AcadexEventType.ATTENDANCE_CLOSED]: {
    eventType: AcadexEventType.ATTENDANCE_CLOSED,
    aggregateType: 'AttendanceSession',
    defaultAction: 'CLOSED',
    allowedScopeTypes: ['college', 'department', 'user', 'channel'],
    version: 1,
    description: 'Attendance session was finalized and closed',
    requiredPayloadKeys: ['sessionId'],
  },
  [AcadexEventType.ATTENDANCE_RECORD_BATCH_UPDATED]: {
    eventType: AcadexEventType.ATTENDANCE_RECORD_BATCH_UPDATED,
    aggregateType: 'AttendanceRecord',
    defaultAction: 'BATCH_UPDATED',
    allowedScopeTypes: ['college', 'department', 'user', 'channel'],
    version: 1,
    description: 'A batch of attendance records was submitted or updated (coalesced)',
    requiredPayloadKeys: ['sessionId', 'recordCount'],
  },

  [AcadexEventType.ASSIGNMENT_CREATED]: {
    eventType: AcadexEventType.ASSIGNMENT_CREATED,
    aggregateType: 'Assignment',
    defaultAction: 'CREATED',
    allowedScopeTypes: ['college', 'department', 'channel'],
    version: 1,
    description: 'An assignment was created',
    requiredPayloadKeys: ['assignmentId'],
  },
  [AcadexEventType.ASSIGNMENT_UPDATED]: {
    eventType: AcadexEventType.ASSIGNMENT_UPDATED,
    aggregateType: 'Assignment',
    defaultAction: 'UPDATED',
    allowedScopeTypes: ['college', 'department', 'channel'],
    version: 1,
    description: 'Assignment details changed',
    requiredPayloadKeys: ['assignmentId'],
  },
  [AcadexEventType.ASSIGNMENT_PUBLISHED]: {
    eventType: AcadexEventType.ASSIGNMENT_PUBLISHED,
    aggregateType: 'Assignment',
    defaultAction: 'PUBLISHED',
    allowedScopeTypes: ['college', 'department', 'channel'],
    version: 1,
    description: 'Assignment was published to students',
    requiredPayloadKeys: ['assignmentId'],
  },
  [AcadexEventType.ASSIGNMENT_CLOSED]: {
    eventType: AcadexEventType.ASSIGNMENT_CLOSED,
    aggregateType: 'Assignment',
    defaultAction: 'CLOSED',
    allowedScopeTypes: ['college', 'department', 'channel'],
    version: 1,
    description: 'Assignment submissions closed',
    requiredPayloadKeys: ['assignmentId'],
  },

  [AcadexEventType.SUBMISSION_SUBMITTED]: {
    eventType: AcadexEventType.SUBMISSION_SUBMITTED,
    aggregateType: 'AssignmentSubmission',
    defaultAction: 'SUBMITTED',
    allowedScopeTypes: ['college', 'department', 'channel', 'user'],
    version: 1,
    description: 'A student submitted work for an assignment',
    requiredPayloadKeys: ['assignmentId', 'submissionId'],
  },
  [AcadexEventType.SUBMISSION_REVIEWED]: {
    eventType: AcadexEventType.SUBMISSION_REVIEWED,
    aggregateType: 'AssignmentSubmission',
    defaultAction: 'REVIEWED',
    allowedScopeTypes: ['college', 'department', 'channel', 'user'],
    version: 1,
    description: 'Faculty reviewed and marked a student submission',
    requiredPayloadKeys: ['assignmentId', 'submissionId', 'studentId'],
  },

  [AcadexEventType.ASSESSMENT_CREATED]: {
    eventType: AcadexEventType.ASSESSMENT_CREATED,
    aggregateType: 'InternalAssessment',
    defaultAction: 'CREATED',
    allowedScopeTypes: ['college', 'department', 'channel'],
    version: 1,
    description: 'A new internal assessment was initialized',
    requiredPayloadKeys: ['assessmentId'],
  },
  [AcadexEventType.ASSESSMENT_UPDATED]: {
    eventType: AcadexEventType.ASSESSMENT_UPDATED,
    aggregateType: 'InternalAssessment',
    defaultAction: 'UPDATED',
    allowedScopeTypes: ['college', 'department', 'channel'],
    version: 1,
    description: 'Internal assessment records were updated',
    requiredPayloadKeys: ['assessmentId'],
  },
  [AcadexEventType.ASSESSMENT_OPENED]: {
    eventType: AcadexEventType.ASSESSMENT_OPENED,
    aggregateType: 'InternalAssessment',
    defaultAction: 'STATUS_CHANGED',
    allowedScopeTypes: ['college', 'department', 'channel'],
    version: 1,
    description: 'Internal assessment was opened for mark entry',
    requiredPayloadKeys: ['assessmentId'],
  },
  [AcadexEventType.ASSESSMENT_CLOSED]: {
    eventType: AcadexEventType.ASSESSMENT_CLOSED,
    aggregateType: 'InternalAssessment',
    defaultAction: 'CLOSED',
    allowedScopeTypes: ['college', 'department', 'channel'],
    version: 1,
    description: 'Internal assessment mark entry was closed',
    requiredPayloadKeys: ['assessmentId'],
  },
  [AcadexEventType.ASSESSMENT_PUBLISHED]: {
    eventType: AcadexEventType.ASSESSMENT_PUBLISHED,
    aggregateType: 'InternalAssessment',
    defaultAction: 'PUBLISHED',
    allowedScopeTypes: ['college', 'department', 'channel'],
    version: 1,
    description: 'Internal assessment marks were published',
    requiredPayloadKeys: ['assessmentId'],
  },
  [AcadexEventType.ASSESSMENT_MARK_CORRECTED]: {
    eventType: AcadexEventType.ASSESSMENT_MARK_CORRECTED,
    aggregateType: 'InternalAssessment',
    defaultAction: 'UPDATED',
    allowedScopeTypes: ['college', 'department', 'channel', 'user'],
    version: 1,
    description: 'A published student mark was corrected with audit trace',
    requiredPayloadKeys: ['assessmentId', 'studentId'],
  },

  [AcadexEventType.NOTE_CREATED]: {
    eventType: AcadexEventType.NOTE_CREATED,
    aggregateType: 'Note',
    defaultAction: 'CREATED',
    allowedScopeTypes: ['college', 'department', 'channel'],
    version: 1,
    description: 'A study material/note was uploaded',
    requiredPayloadKeys: ['noteId'],
  },
  [AcadexEventType.NOTE_UPDATED]: {
    eventType: AcadexEventType.NOTE_UPDATED,
    aggregateType: 'Note',
    defaultAction: 'UPDATED',
    allowedScopeTypes: ['college', 'department', 'channel'],
    version: 1,
    description: 'Note metadata was updated',
    requiredPayloadKeys: ['noteId'],
  },
  [AcadexEventType.NOTE_ARCHIVED]: {
    eventType: AcadexEventType.NOTE_ARCHIVED,
    aggregateType: 'Note',
    defaultAction: 'ARCHIVED',
    allowedScopeTypes: ['college', 'department', 'channel'],
    version: 1,
    description: 'Note was archived or deleted',
    requiredPayloadKeys: ['noteId'],
  },

  // Practical Session Event Definitions
  [AcadexEventType.PRACTICAL_SESSION_CREATED]: {
    eventType: AcadexEventType.PRACTICAL_SESSION_CREATED,
    aggregateType: 'PracticalSession',
    defaultAction: 'CREATED',
    allowedScopeTypes: ['college', 'department', 'channel', 'user'],
    version: 1,
    description: 'A new practical lab session was planned/created',
    requiredPayloadKeys: ['sessionId'],
  },
  [AcadexEventType.PRACTICAL_SESSION_OPENED]: {
    eventType: AcadexEventType.PRACTICAL_SESSION_OPENED,
    aggregateType: 'PracticalSession',
    defaultAction: 'OPENED',
    allowedScopeTypes: ['college', 'department', 'channel', 'user'],
    version: 1,
    description: 'A practical lab session was opened for execution',
    requiredPayloadKeys: ['sessionId'],
  },
  [AcadexEventType.PRACTICAL_SESSION_UPDATED]: {
    eventType: AcadexEventType.PRACTICAL_SESSION_UPDATED,
    aggregateType: 'PracticalSession',
    defaultAction: 'UPDATED',
    allowedScopeTypes: ['college', 'department', 'channel', 'user'],
    version: 1,
    description: 'Practical lab session details were updated',
    requiredPayloadKeys: ['sessionId'],
  },
  [AcadexEventType.PRACTICAL_SESSION_COMPLETED]: {
    eventType: AcadexEventType.PRACTICAL_SESSION_COMPLETED,
    aggregateType: 'PracticalSession',
    defaultAction: 'COMPLETED',
    allowedScopeTypes: ['college', 'department', 'channel', 'user'],
    version: 1,
    description: 'A practical lab session was completed and finalized',
    requiredPayloadKeys: ['sessionId'],
  },
  [AcadexEventType.PRACTICAL_SESSION_CANCELLED]: {
    eventType: AcadexEventType.PRACTICAL_SESSION_CANCELLED,
    aggregateType: 'PracticalSession',
    defaultAction: 'CANCELLED',
    allowedScopeTypes: ['college', 'department', 'channel', 'user'],
    version: 1,
    description: 'A practical lab session was cancelled',
    requiredPayloadKeys: ['sessionId'],
  },
  [AcadexEventType.PRACTICAL_PARTICIPATION_UPDATED]: {
    eventType: AcadexEventType.PRACTICAL_PARTICIPATION_UPDATED,
    aggregateType: 'PracticalParticipation',
    defaultAction: 'BATCH_UPDATED',
    allowedScopeTypes: ['college', 'department', 'channel', 'user'],
    version: 1,
    description: 'Student practical participation or completion states were updated',
    requiredPayloadKeys: ['sessionId'],
  },
  [AcadexEventType.ACADEMIC_RECORD_CREATED]: {
    eventType: AcadexEventType.ACADEMIC_RECORD_CREATED,
    aggregateType: 'AcademicRecord',
    defaultAction: 'CREATED',
    allowedScopeTypes: ['college', 'department', 'user'],
    version: 1,
    description: 'A student academic record was initialized or created',
    requiredPayloadKeys: ['recordId', 'studentId'],
  },
  [AcadexEventType.ACADEMIC_RECORD_UPDATED]: {
    eventType: AcadexEventType.ACADEMIC_RECORD_UPDATED,
    aggregateType: 'AcademicRecord',
    defaultAction: 'UPDATED',
    allowedScopeTypes: ['college', 'department', 'user'],
    version: 1,
    description: 'An academic record was updated',
    requiredPayloadKeys: ['recordId', 'studentId'],
  },
  [AcadexEventType.ACADEMIC_RECORD_PROGRESSION_UPDATED]: {
    eventType: AcadexEventType.ACADEMIC_RECORD_PROGRESSION_UPDATED,
    aggregateType: 'AcademicRecord',
    defaultAction: 'UPDATED',
    allowedScopeTypes: ['college', 'department', 'user'],
    version: 1,
    description: 'A student progression status was updated',
    requiredPayloadKeys: ['recordId', 'studentId', 'progressionStatus'],
  },
  [AcadexEventType.SUBJECT_ACADEMIC_RECORD_UPDATED]: {
    eventType: AcadexEventType.SUBJECT_ACADEMIC_RECORD_UPDATED,
    aggregateType: 'SubjectAcademicRecord',
    defaultAction: 'UPDATED',
    allowedScopeTypes: ['college', 'department', 'user'],
    version: 1,
    description: 'A subject academic record status was updated',
    requiredPayloadKeys: ['subjectRecordId', 'studentId', 'subjectId'],
  },
  [AcadexEventType.ACADEMIC_RESULT_CALCULATED]: {
    eventType: AcadexEventType.ACADEMIC_RESULT_CALCULATED,
    aggregateType: 'AcademicResult',
    defaultAction: 'CREATED',
    allowedScopeTypes: ['college', 'department'],
    version: 1,
    description: 'A semester academic result was calculated or refreshed',
    requiredPayloadKeys: ['resultId', 'studentId', 'semesterId'],
  },
  [AcadexEventType.ACADEMIC_RESULT_UNDER_REVIEW]: {
    eventType: AcadexEventType.ACADEMIC_RESULT_UNDER_REVIEW,
    aggregateType: 'AcademicResult',
    defaultAction: 'UPDATED',
    allowedScopeTypes: ['college', 'department'],
    version: 1,
    description: 'An academic result was moved to under review',
    requiredPayloadKeys: ['resultId', 'studentId', 'semesterId'],
  },
  [AcadexEventType.ACADEMIC_RESULT_FINALIZED]: {
    eventType: AcadexEventType.ACADEMIC_RESULT_FINALIZED,
    aggregateType: 'AcademicResult',
    defaultAction: 'UPDATED',
    allowedScopeTypes: ['college', 'department'],
    version: 1,
    description: 'An academic result was finalized and locked',
    requiredPayloadKeys: ['resultId', 'studentId', 'semesterId'],
  },
  [AcadexEventType.ACADEMIC_RESULT_PUBLISHED]: {
    eventType: AcadexEventType.ACADEMIC_RESULT_PUBLISHED,
    aggregateType: 'AcademicResult',
    defaultAction: 'UPDATED',
    allowedScopeTypes: ['college', 'department', 'user'],
    version: 1,
    description: 'An official academic result was published for student visibility',
    requiredPayloadKeys: ['resultId', 'studentId', 'version'],
  },
  [AcadexEventType.ACADEMIC_RESULT_REOPENED]: {
    eventType: AcadexEventType.ACADEMIC_RESULT_REOPENED,
    aggregateType: 'AcademicResult',
    defaultAction: 'UPDATED',
    allowedScopeTypes: ['college', 'department'],
    version: 1,
    description: 'A finalized or published result was reopened for correction',
    requiredPayloadKeys: ['resultId', 'studentId', 'reason'],
  },

  [AcadexEventType.CALENDAR_CREATED]: {
    eventType: AcadexEventType.CALENDAR_CREATED,
    aggregateType: 'AcademicCalendar',
    defaultAction: 'CREATED',
    allowedScopeTypes: ['college', 'department'],
    version: 1,
    description: 'An academic calendar was created',
    requiredPayloadKeys: ['calendarId', 'academicYearId'],
  },
  [AcadexEventType.CALENDAR_UPDATED]: {
    eventType: AcadexEventType.CALENDAR_UPDATED,
    aggregateType: 'AcademicCalendar',
    defaultAction: 'UPDATED',
    allowedScopeTypes: ['college', 'department'],
    version: 1,
    description: 'An academic calendar was updated or activated',
    requiredPayloadKeys: ['calendarId'],
  },
  [AcadexEventType.CALENDAR_EVENT_CREATED]: {
    eventType: AcadexEventType.CALENDAR_EVENT_CREATED,
    aggregateType: 'CalendarEvent',
    defaultAction: 'CREATED',
    allowedScopeTypes: ['college', 'department', 'channel'],
    version: 1,
    description: 'A calendar event was created or published',
    requiredPayloadKeys: ['eventId', 'startDate'],
  },
  [AcadexEventType.CALENDAR_EVENT_UPDATED]: {
    eventType: AcadexEventType.CALENDAR_EVENT_UPDATED,
    aggregateType: 'CalendarEvent',
    defaultAction: 'UPDATED',
    allowedScopeTypes: ['college', 'department', 'channel'],
    version: 1,
    description: 'A calendar event was updated',
    requiredPayloadKeys: ['eventId', 'startDate'],
  },
  [AcadexEventType.CALENDAR_EVENT_CANCELLED]: {
    eventType: AcadexEventType.CALENDAR_EVENT_CANCELLED,
    aggregateType: 'CalendarEvent',
    defaultAction: 'CLOSED',
    allowedScopeTypes: ['college', 'department', 'channel'],
    version: 1,
    description: 'A calendar event was cancelled',
    requiredPayloadKeys: ['eventId'],
  },
  [AcadexEventType.CALENDAR_OVERRIDE_UPDATED]: {
    eventType: AcadexEventType.CALENDAR_OVERRIDE_UPDATED,
    aggregateType: 'CalendarOverride',
    defaultAction: 'UPDATED',
    allowedScopeTypes: ['college', 'department', 'channel'],
    version: 1,
    description: 'A calendar override or holiday was declared/updated',
    requiredPayloadKeys: ['overrideId', 'date'],
  },
  [AcadexEventType.PROFILE_UPDATED]: {
    eventType: AcadexEventType.PROFILE_UPDATED,
    aggregateType: 'UserProfile',
    defaultAction: 'UPDATED',
    allowedScopeTypes: ['user', 'college'],
    version: 1,
    description: 'User profile personal information was updated',
    requiredPayloadKeys: ['userId'],
  },
  [AcadexEventType.PROFILE_AVATAR_UPDATED]: {
    eventType: AcadexEventType.PROFILE_AVATAR_UPDATED,
    aggregateType: 'UserProfile',
    defaultAction: 'UPDATED',
    allowedScopeTypes: ['user', 'college'],
    version: 1,
    description: 'User avatar/profile picture was updated',
    requiredPayloadKeys: ['userId'],
  },
};
