import 'dart:developer' as developer;
import 'package:flutter/foundation.dart';
import 'package:firebase_core/firebase_core.dart';
import '../../firebase_options.dart';
import 'firebase_config.dart';
import 'firebase_options_placeholder.dart';

enum FirebaseInitializationState {
  initializing,
  ready,
  failed,
}

class FirebaseInitializer {
  static FirebaseInitializationState _state = FirebaseInitializationState.initializing;
  static bool _fallbackMockActive = false;

  static bool get isInitialized => _state == FirebaseInitializationState.ready;
  static FirebaseInitializationState get state => _state;
  
  static bool? overrideShouldUseMock;

  /// SECURE BOUNDARY: Mock repositories may ONLY be activated if explicitly requested
  /// AND the application is running in kDebugMode.
  static bool get shouldUseMock {
    if (!kDebugMode) return false;
    return overrideShouldUseMock ?? (_fallbackMockActive || Firebase.apps.isEmpty);
  }

  static Future<void> initialize([FirebaseEnv env = FirebaseEnv.production]) async {
    if (_state == FirebaseInitializationState.ready) return;
    
    _state = FirebaseInitializationState.initializing;

    // 1. Try DefaultFirebaseOptions if generated by flutterfire configure
    try {
      if (Firebase.apps.isEmpty) {
        await Firebase.initializeApp(
          options: DefaultFirebaseOptions.currentPlatform,
        );
      }
      _state = FirebaseInitializationState.ready;
      _fallbackMockActive = false;
      developer.log(
        'Firebase successfully initialized via DefaultFirebaseOptions.',
        name: 'Acadex.Firebase',
      );
      return;
    } catch (e) {
      developer.log(
        'DefaultFirebaseOptions not available or failed: $e. Trying environment config fallback.',
        name: 'Acadex.Firebase',
      );
    }

    // 2. Fallback to FirebaseConfig from environment
    try {
      final config = FirebaseConfig.fromEnvironment(env);
      
      if (config.isPlaceholder) {
        if (kDebugMode) {
          developer.log(
            'Firebase initialized in Fallback Mock Mode (Placeholder Credentials).',
            name: 'Acadex.Firebase',
          );
          _fallbackMockActive = true;
          _state = FirebaseInitializationState.ready;
        } else {
          developer.log(
            'CRITICAL: Production build missing Firebase config. Mock fallback blocked by kDebugMode.',
            name: 'Acadex.Firebase',
          );
          _fallbackMockActive = false;
          _state = FirebaseInitializationState.failed;
        }
        return;
      }

      if (Firebase.apps.isEmpty) {
        await Firebase.initializeApp(
          options: FirebaseOptionsPlaceholder.getOptionsForConfig(config),
        );
      }

      _state = FirebaseInitializationState.ready;
      _fallbackMockActive = false;
      developer.log(
        'Firebase successfully initialized for environment: ${env.name}',
        name: 'Acadex.Firebase',
      );
    } catch (e, stack) {
      if (kDebugMode) {
        _fallbackMockActive = true;
        _state = FirebaseInitializationState.ready;
        developer.log(
          'Firebase initialization failed. Falling back to local offline mock mode (Debug Only).',
          name: 'Acadex.Firebase',
          error: e,
          stackTrace: stack,
        );
      } else {
        _fallbackMockActive = false;
        _state = FirebaseInitializationState.failed;
        developer.log(
          'CRITICAL: Firebase initialization failed in Production! Mock fallback blocked.',
          name: 'Acadex.Firebase',
          error: e,
          stackTrace: stack,
        );
      }
    }
  }
}
