import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';
import '../../../../app/theme/app_theme.dart';
import '../../../../core/presentation/utils/navigation_extensions.dart';
import '../../../../core/presentation/widgets/acadex_button.dart';
import '../../../../core/presentation/widgets/acadex_page_container.dart';
import '../../../auth/presentation/providers/auth_provider.dart';
import '../../../auth/domain/models/auth_state.dart';
import '../../../auth/domain/models/role_enum.dart';
import '../../domain/models/notification_models.dart';
import '../providers/notification_providers.dart';

class CreateAnnouncementScreen extends ConsumerStatefulWidget {
  const CreateAnnouncementScreen({super.key});

  @override
  ConsumerState<CreateAnnouncementScreen> createState() => _CreateAnnouncementScreenState();
}

class _CreateAnnouncementScreenState extends ConsumerState<CreateAnnouncementScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _messageController = TextEditingController();

  NotificationCategory _category = NotificationCategory.general;
  NotificationPriority _priority = NotificationPriority.normal;
  NotificationAudienceType? _audienceType;

  @override
  void dispose() {
    _titleController.dispose();
    _messageController.dispose();
    super.dispose();
  }

  void _submit() async {
    if (!_formKey.currentState!.validate() || _audienceType == null) return;

    final authState = ref.read(authProvider);
    if (authState is! AuthAuthenticated) return;

    final user = authState.user;

    final notification = NotificationModel(
      id: '', // Generated by repo
      title: _titleController.text.trim(),
      message: _messageController.text.trim(),
      category: _category,
      priority: _priority,
      audienceType: _audienceType!,
      timestamp: DateTime.now(),
      collegeId: _audienceType == NotificationAudienceType.college || _audienceType == NotificationAudienceType.department ? user.collegeId : null,
      departmentId: _audienceType == NotificationAudienceType.department ? user.departmentId : null,
    );

    await ref.read(announcementCreationProvider.notifier).createAnnouncement(notification);

    if (mounted) {
      context.safePop(fallbackRoute: '/notifications');
    }
  }

  @override
  Widget build(BuildContext context) {
    final authState = ref.watch(authProvider);
    if (authState is! AuthAuthenticated) return const SizedBox.shrink();

    final user = authState.user;
    final creationState = ref.watch(announcementCreationProvider);
    final isLoading = creationState.isLoading;

    final audienceOptions = <DropdownMenuItem<NotificationAudienceType>>[];

    if (user.role == AppRole.superAdmin) {
      audienceOptions.add(DropdownMenuItem(
        value: NotificationAudienceType.platform,
        child: Text('Platform Wide', style: AcadexTypography.body(color: AcadexColors.ink)),
      ));
    }
    if (user.role == AppRole.superAdmin || user.role == AppRole.collegeAdmin) {
      audienceOptions.add(DropdownMenuItem(
        value: NotificationAudienceType.college,
        child: Text('My College', style: AcadexTypography.body(color: AcadexColors.ink)),
      ));
    }
    if (user.role == AppRole.superAdmin || user.role == AppRole.collegeAdmin || user.role == AppRole.hod) {
      audienceOptions.add(DropdownMenuItem(
        value: NotificationAudienceType.department,
        child: Text('My Department', style: AcadexTypography.body(color: AcadexColors.ink)),
      ));
    }

    return Scaffold(
      backgroundColor: Colors.transparent,
      appBar: AppBar(
        title: Text(
          'Create Announcement',
          style: AcadexTypography.heading3(color: AcadexColors.ink),
        ),
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(LucideIcons.arrowLeft, color: AcadexColors.ink),
          onPressed: () => context.safePop(fallbackRoute: '/notifications'),
        ),
      ),
      body: AcadexPageContainer(
        maxWidth: AcadexLayout.formMaxWidth,
        child: Container(
          padding: const EdgeInsets.all(28),
          decoration: BoxDecoration(
            color: AcadexColors.surface,
            borderRadius: AcadexRadius.borderRadiusLg,
            border: Border.all(color: AcadexColors.hairline),
            boxShadow: AcadexShadows.lightSm,
          ),
          child: Form(
            key: _formKey,
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                Text(
                  'Announcement Details',
                  style: AcadexTypography.heading3(color: AcadexColors.ink),
                ),
                const SizedBox(height: 6),
                Text(
                  'Compose a notification to broadcast to users across the platform.',
                  style: AcadexTypography.bodySmall(color: AcadexColors.inkSecondary),
                ),
                const SizedBox(height: 24),
                TextFormField(
                  controller: _titleController,
                  style: AcadexTypography.body(color: AcadexColors.ink),
                  decoration: InputDecoration(
                    labelText: 'Title',
                    labelStyle: AcadexTypography.bodySmall(color: AcadexColors.inkSecondary),
                    hintText: 'Enter announcement title',
                    hintStyle: AcadexTypography.body(color: AcadexColors.inkFaint),
                    filled: true,
                    fillColor: AcadexColors.canvas,
                    border: OutlineInputBorder(
                      borderRadius: AcadexRadius.borderRadiusMd,
                      borderSide: const BorderSide(color: AcadexColors.hairline),
                    ),
                    enabledBorder: OutlineInputBorder(
                      borderRadius: AcadexRadius.borderRadiusMd,
                      borderSide: const BorderSide(color: AcadexColors.hairline),
                    ),
                    focusedBorder: OutlineInputBorder(
                      borderRadius: AcadexRadius.borderRadiusMd,
                      borderSide: const BorderSide(color: AcadexColors.primary, width: 1.5),
                    ),
                  ),
                  validator: (value) => value == null || value.trim().isEmpty ? 'Title is required' : null,
                ),
                const SizedBox(height: 18),
                TextFormField(
                  controller: _messageController,
                  maxLines: 4,
                  style: AcadexTypography.body(color: AcadexColors.ink),
                  decoration: InputDecoration(
                    labelText: 'Message',
                    labelStyle: AcadexTypography.bodySmall(color: AcadexColors.inkSecondary),
                    hintText: 'Write the announcement body text...',
                    hintStyle: AcadexTypography.body(color: AcadexColors.inkFaint),
                    filled: true,
                    fillColor: AcadexColors.canvas,
                    border: OutlineInputBorder(
                      borderRadius: AcadexRadius.borderRadiusMd,
                      borderSide: const BorderSide(color: AcadexColors.hairline),
                    ),
                    enabledBorder: OutlineInputBorder(
                      borderRadius: AcadexRadius.borderRadiusMd,
                      borderSide: const BorderSide(color: AcadexColors.hairline),
                    ),
                    focusedBorder: OutlineInputBorder(
                      borderRadius: AcadexRadius.borderRadiusMd,
                      borderSide: const BorderSide(color: AcadexColors.primary, width: 1.5),
                    ),
                  ),
                  validator: (value) => value == null || value.trim().isEmpty ? 'Message is required' : null,
                ),
                const SizedBox(height: 18),
                DropdownButtonFormField<NotificationAudienceType>(
                  initialValue: _audienceType,
                  dropdownColor: AcadexColors.surface,
                  style: AcadexTypography.body(color: AcadexColors.ink),
                  iconEnabledColor: AcadexColors.inkSecondary,
                  decoration: InputDecoration(
                    labelText: 'Target Audience',
                    labelStyle: AcadexTypography.bodySmall(color: AcadexColors.inkSecondary),
                    filled: true,
                    fillColor: AcadexColors.canvas,
                    border: OutlineInputBorder(
                      borderRadius: AcadexRadius.borderRadiusMd,
                      borderSide: const BorderSide(color: AcadexColors.hairline),
                    ),
                    enabledBorder: OutlineInputBorder(
                      borderRadius: AcadexRadius.borderRadiusMd,
                      borderSide: const BorderSide(color: AcadexColors.hairline),
                    ),
                    focusedBorder: OutlineInputBorder(
                      borderRadius: AcadexRadius.borderRadiusMd,
                      borderSide: const BorderSide(color: AcadexColors.primary, width: 1.5),
                    ),
                  ),
                  items: audienceOptions,
                  onChanged: (val) => setState(() => _audienceType = val),
                  validator: (value) => value == null ? 'Please select a target audience' : null,
                ),
                const SizedBox(height: 18),
                Row(
                  children: [
                    Expanded(
                      child: DropdownButtonFormField<NotificationCategory>(
                        initialValue: _category,
                        dropdownColor: AcadexColors.surface,
                        style: AcadexTypography.body(color: AcadexColors.ink),
                        iconEnabledColor: AcadexColors.inkSecondary,
                        decoration: InputDecoration(
                          labelText: 'Category',
                          labelStyle: AcadexTypography.bodySmall(color: AcadexColors.inkSecondary),
                          filled: true,
                          fillColor: AcadexColors.canvas,
                          border: OutlineInputBorder(
                            borderRadius: AcadexRadius.borderRadiusMd,
                            borderSide: const BorderSide(color: AcadexColors.hairline),
                          ),
                          enabledBorder: OutlineInputBorder(
                            borderRadius: AcadexRadius.borderRadiusMd,
                            borderSide: const BorderSide(color: AcadexColors.hairline),
                          ),
                          focusedBorder: OutlineInputBorder(
                            borderRadius: AcadexRadius.borderRadiusMd,
                            borderSide: const BorderSide(color: AcadexColors.primary, width: 1.5),
                          ),
                        ),
                        items: NotificationCategory.values.map((c) {
                          return DropdownMenuItem(
                            value: c,
                            child: Text(
                              c.name.toUpperCase(),
                              style: AcadexTypography.body(color: AcadexColors.ink),
                            ),
                          );
                        }).toList(),
                        onChanged: (val) => setState(() => _category = val!),
                      ),
                    ),
                    const SizedBox(width: 16),
                    Expanded(
                      child: DropdownButtonFormField<NotificationPriority>(
                        initialValue: _priority,
                        dropdownColor: AcadexColors.surface,
                        style: AcadexTypography.body(color: AcadexColors.ink),
                        iconEnabledColor: AcadexColors.inkSecondary,
                        decoration: InputDecoration(
                          labelText: 'Priority',
                          labelStyle: AcadexTypography.bodySmall(color: AcadexColors.inkSecondary),
                          filled: true,
                          fillColor: AcadexColors.canvas,
                          border: OutlineInputBorder(
                            borderRadius: AcadexRadius.borderRadiusMd,
                            borderSide: const BorderSide(color: AcadexColors.hairline),
                          ),
                          enabledBorder: OutlineInputBorder(
                            borderRadius: AcadexRadius.borderRadiusMd,
                            borderSide: const BorderSide(color: AcadexColors.hairline),
                          ),
                          focusedBorder: OutlineInputBorder(
                            borderRadius: AcadexRadius.borderRadiusMd,
                            borderSide: const BorderSide(color: AcadexColors.primary, width: 1.5),
                          ),
                        ),
                        items: NotificationPriority.values.map((p) {
                          return DropdownMenuItem(
                            value: p,
                            child: Text(
                              p.name.toUpperCase(),
                              style: AcadexTypography.body(color: AcadexColors.ink),
                            ),
                          );
                        }).toList(),
                        onChanged: (val) => setState(() => _priority = val!),
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 32),
                if (creationState.hasError)
                  Padding(
                    padding: const EdgeInsets.only(bottom: 16),
                    child: Text(
                      creationState.error.toString(),
                      style: AcadexTypography.bodySmall(color: AcadexColors.error),
                    ),
                  ),
                AcadexButton(
                  label: 'Broadcast Announcement',
                  icon: LucideIcons.send,
                  isLoading: isLoading,
                  onPressed: isLoading ? null : _submit,
                  isFullWidth: true,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
