import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:google_fonts/google_fonts.dart';
import '../../../../app/theme/app_theme.dart';
import '../../../auth/presentation/providers/auth_provider.dart';
import '../../../auth/domain/models/auth_state.dart';
import '../../../auth/domain/models/role_enum.dart';
import '../../domain/models/notification_models.dart';
import '../providers/notification_providers.dart';

class CreateAnnouncementScreen extends ConsumerStatefulWidget {
  const CreateAnnouncementScreen({super.key});

  @override
  ConsumerState<CreateAnnouncementScreen> createState() => _CreateAnnouncementScreenState();
}

class _CreateAnnouncementScreenState extends ConsumerState<CreateAnnouncementScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _messageController = TextEditingController();
  
  NotificationCategory _category = NotificationCategory.general;
  NotificationPriority _priority = NotificationPriority.normal;
  NotificationAudienceType? _audienceType;

  @override
  void dispose() {
    _titleController.dispose();
    _messageController.dispose();
    super.dispose();
  }

  void _submit() async {
    if (!_formKey.currentState!.validate() || _audienceType == null) return;

    final authState = ref.read(authProvider);
    if (authState is! AuthAuthenticated) return;
    
    final user = authState.user;

    final notification = NotificationModel(
      id: '', // Generated by repo
      title: _titleController.text,
      message: _messageController.text,
      category: _category,
      priority: _priority,
      audienceType: _audienceType!,
      timestamp: DateTime.now(),
      collegeId: _audienceType == NotificationAudienceType.college || _audienceType == NotificationAudienceType.department ? user.collegeId : null,
      departmentId: _audienceType == NotificationAudienceType.department ? user.departmentId : null,
    );

    await ref.read(announcementCreationProvider.notifier).createAnnouncement(notification);
    
    if (mounted) {
      context.pop();
    }
  }

  @override
  Widget build(BuildContext context) {
    final authState = ref.watch(authProvider);
    if (authState is! AuthAuthenticated) return const SizedBox.shrink();
    
    final user = authState.user;
    final creationState = ref.watch(announcementCreationProvider);
    final isLoading = creationState.isLoading;

    List<DropdownMenuItem<NotificationAudienceType>> audienceOptions = [];
    
    if (user.role == AppRole.superAdmin) {
      audienceOptions.add(const DropdownMenuItem(value: NotificationAudienceType.platform, child: Text('Platform Wide')));
    }
    if (user.role == AppRole.superAdmin || user.role == AppRole.collegeAdmin) {
      audienceOptions.add(const DropdownMenuItem(value: NotificationAudienceType.college, child: Text('My College')));
    }
    if (user.role == AppRole.superAdmin || user.role == AppRole.collegeAdmin || user.role == AppRole.hod) {
      audienceOptions.add(const DropdownMenuItem(value: NotificationAudienceType.department, child: Text('My Department')));
    }

    return Scaffold(
      backgroundColor: DashboardColors.background,
      appBar: AppBar(
        title: Text('Create Announcement', style: GoogleFonts.inter(fontWeight: FontWeight.w600, color: Colors.white)),
        backgroundColor: DashboardColors.surface,
        iconTheme: const IconThemeData(color: Colors.white),
      ),
      body: Center(
        child: ConstrainedBox(
          constraints: const BoxConstraints(maxWidth: 600),
          child: Card(
            margin: const EdgeInsets.all(24),
            color: DashboardColors.surface,
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
            child: Padding(
              padding: const EdgeInsets.all(24.0),
              child: Form(
                key: _formKey,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    TextFormField(
                      controller: _titleController,
                      style: const TextStyle(color: Colors.white),
                      decoration: InputDecoration(
                        labelText: 'Title',
                        labelStyle: TextStyle(color: Colors.white.withOpacity(0.7)),
                        border: OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
                      ),
                      validator: (value) => value == null || value.isEmpty ? 'Required' : null,
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _messageController,
                      maxLines: 4,
                      style: const TextStyle(color: Colors.white),
                      decoration: InputDecoration(
                        labelText: 'Message',
                        labelStyle: TextStyle(color: Colors.white.withOpacity(0.7)),
                        border: OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
                      ),
                      validator: (value) => value == null || value.isEmpty ? 'Required' : null,
                    ),
                    const SizedBox(height: 16),
                    DropdownButtonFormField<NotificationAudienceType>(
                      value: _audienceType,
                      dropdownColor: DashboardColors.surface,
                      style: const TextStyle(color: Colors.white),
                      decoration: InputDecoration(
                        labelText: 'Target Audience',
                        labelStyle: TextStyle(color: Colors.white.withOpacity(0.7)),
                        border: OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
                      ),
                      items: audienceOptions,
                      onChanged: (val) => setState(() => _audienceType = val),
                      validator: (value) => value == null ? 'Required' : null,
                    ),
                    const SizedBox(height: 16),
                    Row(
                      children: [
                        Expanded(
                          child: DropdownButtonFormField<NotificationCategory>(
                            value: _category,
                            dropdownColor: DashboardColors.surface,
                            style: const TextStyle(color: Colors.white),
                            decoration: InputDecoration(
                              labelText: 'Category',
                              labelStyle: TextStyle(color: Colors.white.withOpacity(0.7)),
                              border: OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
                            ),
                            items: NotificationCategory.values.map((c) {
                              return DropdownMenuItem(value: c, child: Text(c.name.toUpperCase()));
                            }).toList(),
                            onChanged: (val) => setState(() => _category = val!),
                          ),
                        ),
                        const SizedBox(width: 16),
                        Expanded(
                          child: DropdownButtonFormField<NotificationPriority>(
                            value: _priority,
                            dropdownColor: DashboardColors.surface,
                            style: const TextStyle(color: Colors.white),
                            decoration: InputDecoration(
                              labelText: 'Priority',
                              labelStyle: TextStyle(color: Colors.white.withOpacity(0.7)),
                              border: OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
                            ),
                            items: NotificationPriority.values.map((p) {
                              return DropdownMenuItem(value: p, child: Text(p.name.toUpperCase()));
                            }).toList(),
                            onChanged: (val) => setState(() => _priority = val!),
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 32),
                    if (creationState.hasError)
                      Padding(
                        padding: const EdgeInsets.only(bottom: 16),
                        child: Text(
                          creationState.error.toString(),
                          style: const TextStyle(color: DashboardColors.error),
                        ),
                      ),
                    ElevatedButton(
                      style: ElevatedButton.styleFrom(
                        backgroundColor: DashboardColors.primary,
                        padding: const EdgeInsets.symmetric(vertical: 16),
                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                      ),
                      onPressed: isLoading ? null : _submit,
                      child: isLoading
                          ? const SizedBox(width: 24, height: 24, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))
                          : Text('Broadcast Announcement', style: GoogleFonts.inter(fontWeight: FontWeight.w600, color: Colors.white)),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
