import '../models/attendance_analytics_models.dart';
import '../models/attendance_report_models.dart';
import '../models/attendance_session.dart';
import '../models/department_attendance_comparison.dart';

/// Service responsible for generating standardized CSV and structured printable reports
/// from Attendance domain and analytics models.
class AttendanceReportExporter {
  AttendanceReportExporter._();

  /// Escapes a single CSV value according to RFC 4180.
  /// Handles quotes, commas, CRLF, empty strings, and Unicode characters safely.
  static String escapeCsv(dynamic value) {
    if (value == null) return '';
    final str = value.toString();
    if (str.contains(',') || str.contains('"') || str.contains('\n') || str.contains('\r')) {
      return '"${str.replaceAll('"', '""')}"';
    }
    return str;
  }

  /// Formats a list of values as a standard CSV row
  static String formatRow(List<dynamic> values) {
    return values.map(escapeCsv).join(',');
  }

  /// Formats date range label
  static String formatDateRange(AttendanceDateRange? dateRange) {
    if (dateRange == null) return 'All Time';
    return '${dateRange.startDate.toIso8601String().split('T').first} to ${dateRange.endDate.toIso8601String().split('T').first}';
  }

  /// Converts an AttendanceReportResult into a deterministic CSV string
  static String generateReportCsv(AttendanceReportResult report) {
    final buffer = StringBuffer();

    // Institutional Header
    buffer.writeln(formatRow(['ACADEX ATTENDANCE REPORT']));
    buffer.writeln(formatRow(['Report Title', report.title]));
    buffer.writeln(formatRow(['Scope', report.scopeDescription]));
    buffer.writeln(formatRow(['Generated At', report.generatedAt.toIso8601String()]));
    buffer.writeln(formatRow(['Generated By', report.generatedBy]));
    if (report.dateRange != null) {
      buffer.writeln(formatRow(['Date Range', formatDateRange(report.dateRange)]));
    }
    buffer.writeln(formatRow(['Total Records', report.totalRecords]));

    // Summary Statistics
    if (report.summaryStatistics.isNotEmpty) {
      buffer.writeln();
      buffer.writeln(formatRow(['--- SUMMARY STATISTICS ---']));
      for (final entry in report.summaryStatistics.entries) {
        buffer.writeln(formatRow([entry.key, entry.value]));
      }
    }

    buffer.writeln();

    // Data Table Headers
    buffer.writeln(formatRow(report.headers));

    // Data Table Rows
    if (report.rows.isEmpty) {
      buffer.writeln(formatRow(List.filled(report.headers.length, 'No records found')));
    } else {
      for (final row in report.rows) {
        buffer.writeln(formatRow(row));
      }
    }

    return buffer.toString();
  }

  /// Generates CSV report for a single student's attendance & subject breakdown
  static String generateStudentAttendanceCsv({
    required StudentAttendanceAnalytics student,
    List<SubjectAttendanceAnalytics> subjects = const [],
    AttendanceDateRange? dateRange,
  }) {
    final buffer = StringBuffer();

    buffer.writeln(formatRow(['ACADEX STUDENT ATTENDANCE REPORT']));
    buffer.writeln(formatRow(['Student Name', student.studentName]));
    buffer.writeln(formatRow(['Roll Number', student.rollNumber]));
    buffer.writeln(formatRow(['Section', student.sectionId]));
    buffer.writeln(formatRow(['Overall Attendance', '${student.attendancePercentage.toStringAsFixed(1)}%']));
    buffer.writeln(formatRow(['Risk Standing', student.riskLevel.name.toUpperCase()]));
    buffer.writeln(formatRow(['Total Sessions', student.totalSessions]));
    buffer.writeln(formatRow(['Present', student.presentCount]));
    buffer.writeln(formatRow(['Absent', student.absentCount]));
    buffer.writeln(formatRow(['Late', student.lateCount]));
    buffer.writeln(formatRow(['Excused', student.excusedCount]));
    if (student.isLowAttendance) {
      buffer.writeln(formatRow(['Sessions Needed for 75%', student.recoverySessionsNeeded]));
    }
    if (dateRange != null) {
      buffer.writeln(formatRow(['Date Range', formatDateRange(dateRange)]));
    }
    buffer.writeln();

    buffer.writeln(formatRow([
      'Subject Name',
      'Subject Code',
      'Total Classes',
      'Attendance %',
      'Present',
      'Absent',
      'Late',
      'Excused',
      'Risk Level',
    ]));

    if (subjects.isEmpty) {
      buffer.writeln(formatRow(['No individual subject records available', '', '', '', '', '', '', '', '']));
    } else {
      for (final sub in subjects) {
        buffer.writeln(formatRow([
          sub.subjectName.isNotEmpty ? sub.subjectName : sub.subjectId,
          sub.subjectId,
          sub.totalSessions,
          '${sub.attendancePercentage.toStringAsFixed(1)}%',
          sub.presentCount,
          sub.absentCount,
          sub.lateCount,
          sub.excusedCount,
          sub.riskLevel.name.toUpperCase(),
        ]));
      }
    }

    return buffer.toString();
  }

  /// Generates CSV report for a section and its student roster ranking
  static String generateSectionAttendanceCsv({
    required SectionAttendanceAnalytics section,
    List<StudentAttendanceAnalytics>? studentsOverride,
    AttendanceDateRange? dateRange,
  }) {
    final buffer = StringBuffer();
    final effectiveStudents = studentsOverride ?? section.studentAnalytics;

    buffer.writeln(formatRow(['ACADEX SECTION ATTENDANCE REPORT']));
    buffer.writeln(formatRow(['Section Name', section.sectionName.isNotEmpty ? section.sectionName : section.sectionId]));
    buffer.writeln(formatRow(['Overall Attendance', '${section.attendancePercentage.toStringAsFixed(1)}%']));
    buffer.writeln(formatRow(['Total Students', section.totalStudents]));
    buffer.writeln(formatRow(['Total Sessions', section.totalSessions]));
    buffer.writeln(formatRow(['Students Below 75%', section.lowAttendanceStudentCount]));
    if (dateRange != null) {
      buffer.writeln(formatRow(['Date Range', formatDateRange(dateRange)]));
    }
    buffer.writeln();

    buffer.writeln(formatRow([
      'Rank',
      'Student Name',
      'Roll Number',
      'Attendance %',
      'Risk Level',
      'Total Sessions',
      'Present',
      'Absent',
      'Late',
      'Excused',
      'Recovery Needed (75%)',
    ]));

    if (effectiveStudents.isEmpty) {
      buffer.writeln(formatRow(['No student records found in section', '', '', '', '', '', '', '', '', '', '']));
    } else {
      final sorted = List<StudentAttendanceAnalytics>.from(effectiveStudents)
        ..sort((a, b) => b.attendancePercentage.compareTo(a.attendancePercentage));

      for (int i = 0; i < sorted.length; i++) {
        final s = sorted[i];
        buffer.writeln(formatRow([
          i + 1,
          s.studentName.isNotEmpty ? s.studentName : s.studentId,
          s.rollNumber,
          '${s.attendancePercentage.toStringAsFixed(1)}%',
          s.riskLevel.name.toUpperCase(),
          s.totalSessions,
          s.presentCount,
          s.absentCount,
          s.lateCount,
          s.excusedCount,
          s.isLowAttendance ? s.recoverySessionsNeeded : 0,
        ]));
      }
    }

    return buffer.toString();
  }

  /// Generates CSV report for actionable low-attendance intervention
  static String generateLowAttendanceReportCsv({
    required List<StudentAttendanceAnalytics> lowAttendanceStudents,
    String scopeTitle = 'Institutional Low Attendance Action Report',
    AttendanceDateRange? dateRange,
  }) {
    final buffer = StringBuffer();

    buffer.writeln(formatRow(['ACADEX LOW ATTENDANCE INTERVENTION REPORT']));
    buffer.writeln(formatRow(['Scope', scopeTitle]));
    buffer.writeln(formatRow(['Threshold', '${AttendanceAnalyticsConstants.lowAttendanceThreshold}%']));
    buffer.writeln(formatRow(['Students in Shortage', lowAttendanceStudents.length]));
    if (dateRange != null) {
      buffer.writeln(formatRow(['Date Range', formatDateRange(dateRange)]));
    }
    buffer.writeln();

    buffer.writeln(formatRow([
      'Priority',
      'Student Name',
      'Roll Number',
      'Section',
      'Current Attendance %',
      'Sessions Present',
      'Sessions Absent',
      'Consecutive Classes Needed for 75%',
      'Status',
    ]));

    if (lowAttendanceStudents.isEmpty) {
      buffer.writeln(formatRow(['No students in critical shortage', '', '', '', '', '', '', '', '']));
    } else {
      final sorted = List<StudentAttendanceAnalytics>.from(lowAttendanceStudents)
        ..sort((a, b) => a.attendancePercentage.compareTo(b.attendancePercentage));

      for (int i = 0; i < sorted.length; i++) {
        final s = sorted[i];
        buffer.writeln(formatRow([
          i + 1,
          s.studentName.isNotEmpty ? s.studentName : s.studentId,
          s.rollNumber,
          s.sectionId,
          '${s.attendancePercentage.toStringAsFixed(1)}%',
          s.presentCount,
          s.absentCount,
          s.recoverySessionsNeeded,
          'CRITICAL SHORTAGE',
        ]));
      }
    }

    return buffer.toString();
  }

  /// Generates CSV report for subject analytics
  static String generateSubjectAttendanceCsv({
    required SubjectAttendanceAnalytics subject,
    AttendanceDateRange? dateRange,
  }) {
    final buffer = StringBuffer();

    buffer.writeln(formatRow(['ACADEX SUBJECT ATTENDANCE REPORT']));
    buffer.writeln(formatRow(['Subject Name', subject.subjectName.isNotEmpty ? subject.subjectName : subject.subjectId]));
    buffer.writeln(formatRow(['Subject Code', subject.subjectId]));
    buffer.writeln(formatRow(['Overall Attendance', '${subject.attendancePercentage.toStringAsFixed(1)}%']));
    buffer.writeln(formatRow(['Total Sessions', subject.totalSessions]));
    buffer.writeln(formatRow(['Total Student Records', subject.totalStudentRecords]));
    buffer.writeln(formatRow(['Risk Standing', subject.riskLevel.name.toUpperCase()]));
    if (dateRange != null) {
      buffer.writeln(formatRow(['Date Range', formatDateRange(dateRange)]));
    }
    buffer.writeln();

    buffer.writeln(formatRow([
      'Metric',
      'Value',
      'Share %',
    ]));

    final total = subject.totalStudentRecords;
    final presentShare = total > 0 ? (subject.presentCount / total * 100).toStringAsFixed(1) : '0';
    final absentShare = total > 0 ? (subject.absentCount / total * 100).toStringAsFixed(1) : '0';
    final lateShare = total > 0 ? (subject.lateCount / total * 100).toStringAsFixed(1) : '0';
    final excusedShare = total > 0 ? (subject.excusedCount / total * 100).toStringAsFixed(1) : '0';

    buffer.writeln(formatRow(['Present', subject.presentCount, '$presentShare%']));
    buffer.writeln(formatRow(['Absent', subject.absentCount, '$absentShare%']));
    buffer.writeln(formatRow(['Late', subject.lateCount, '$lateShare%']));
    buffer.writeln(formatRow(['Excused', subject.excusedCount, '$excusedShare%']));

    return buffer.toString();
  }

  /// Generates CSV report for faculty attendance metrics
  static String generateFacultyAttendanceCsv({
    required FacultyAttendanceAnalytics faculty,
    AttendanceDateRange? dateRange,
  }) {
    final buffer = StringBuffer();

    buffer.writeln(formatRow(['ACADEX FACULTY ATTENDANCE REPORT']));
    buffer.writeln(formatRow(['Faculty Name', faculty.facultyName.isNotEmpty ? faculty.facultyName : faculty.facultyId]));
    buffer.writeln(formatRow(['Faculty ID', faculty.facultyId]));
    buffer.writeln(formatRow(['Sessions Conducted', faculty.totalSessionsConducted]));
    buffer.writeln(formatRow(['Average Class Attendance', '${faculty.attendancePercentage.toStringAsFixed(1)}%']));
    if (dateRange != null) {
      buffer.writeln(formatRow(['Date Range', formatDateRange(dateRange)]));
    }
    buffer.writeln();

    buffer.writeln(formatRow([
      'Metric',
      'Value',
    ]));

    buffer.writeln(formatRow(['Total Sessions Conducted', faculty.totalSessionsConducted]));
    buffer.writeln(formatRow(['Total Student Attendances Tracked', faculty.totalStudentRecords]));
    buffer.writeln(formatRow(['Present Attendances', faculty.presentCount]));
    buffer.writeln(formatRow(['Absent Attendances', faculty.absentCount]));
    buffer.writeln(formatRow(['Late Attendances', faculty.lateCount]));
    buffer.writeln(formatRow(['Excused Attendances', faculty.excusedCount]));

    return buffer.toString();
  }

  /// Generates CSV report for department comparison and overview
  static String generateDepartmentAttendanceCsv({
    required String departmentId,
    required List<SectionAttendanceAnalytics> sections,
    AttendanceDateRange? dateRange,
  }) {
    final buffer = StringBuffer();

    final totalStudents = sections.fold<int>(0, (sum, s) => sum + s.totalStudents);
    final totalSessions = sections.fold<int>(0, (sum, s) => sum + s.totalSessions);
    final totalLow = sections.fold<int>(0, (sum, s) => sum + s.lowAttendanceStudentCount);
    final avgAttendance = sections.isNotEmpty
        ? sections.fold<double>(0, (sum, s) => sum + s.attendancePercentage) / sections.length
        : 0.0;

    buffer.writeln(formatRow(['ACADEX DEPARTMENT ATTENDANCE REPORT']));
    buffer.writeln(formatRow(['Department ID', departmentId]));
    buffer.writeln(formatRow(['Total Sections', sections.length]));
    buffer.writeln(formatRow(['Total Students', totalStudents]));
    buffer.writeln(formatRow(['Total Sessions Conducted', totalSessions]));
    buffer.writeln(formatRow(['Average Department Attendance', '${avgAttendance.toStringAsFixed(1)}%']));
    buffer.writeln(formatRow(['Total Students in Shortage', totalLow]));
    if (dateRange != null) {
      buffer.writeln(formatRow(['Date Range', formatDateRange(dateRange)]));
    }
    buffer.writeln();

    buffer.writeln(formatRow([
      'Section Name',
      'Total Students',
      'Sessions Conducted',
      'Average Attendance %',
      'Students Below 75%',
      'Risk Status',
    ]));

    if (sections.isEmpty) {
      buffer.writeln(formatRow(['No sections found in department', '', '', '', '', '']));
    } else {
      for (final sec in sections) {
        buffer.writeln(formatRow([
          sec.sectionName.isNotEmpty ? sec.sectionName : sec.sectionId,
          sec.totalStudents,
          sec.totalSessions,
          '${sec.attendancePercentage.toStringAsFixed(1)}%',
          sec.lowAttendanceStudentCount,
          sec.attendancePercentage < 70 ? 'CRITICAL' : (sec.attendancePercentage < 75 ? 'WARNING' : 'GOOD'),
        ]));
      }
    }

    return buffer.toString();
  }

  /// Generates CSV report for college overview
  static String generateCollegeAttendanceCsv({
    required String collegeId,
    required List<DepartmentAttendanceComparison> departments,
    AttendanceDateRange? dateRange,
  }) {
    final buffer = StringBuffer();

    final avgAttendance = departments.isNotEmpty
        ? departments.fold<double>(0, (sum, d) => sum + d.attendancePercentage) / departments.length
        : 0.0;

    buffer.writeln(formatRow(['ACADEX COLLEGE ATTENDANCE REPORT']));
    buffer.writeln(formatRow(['College ID', collegeId]));
    buffer.writeln(formatRow(['Total Departments', departments.length]));
    buffer.writeln(formatRow(['Overall College Attendance', '${avgAttendance.toStringAsFixed(1)}%']));
    if (dateRange != null) {
      buffer.writeln(formatRow(['Date Range', formatDateRange(dateRange)]));
    }
    buffer.writeln();

    buffer.writeln(formatRow([
      'Department Name',
      'Attendance %',
      'Student Count',
      'Faculty Count',
    ]));

    if (departments.isEmpty) {
      buffer.writeln(formatRow(['No departments found in college', '', '', '']));
    } else {
      for (final dept in departments) {
        buffer.writeln(formatRow([
          dept.departmentName,
          '${dept.attendancePercentage.toStringAsFixed(1)}%',
          dept.studentCount,
          dept.facultyCount,
        ]));
      }
    }

    return buffer.toString();
  }

  /// Generates CSV report for attendance sessions
  static String generateAttendanceSessionsCsv({
    required List<AttendanceSession> sessions,
    String scopeTitle = 'Attendance Sessions Export',
    AttendanceDateRange? dateRange,
  }) {
    final buffer = StringBuffer();

    buffer.writeln(formatRow(['ACADEX ATTENDANCE SESSIONS LOG']));
    buffer.writeln(formatRow(['Scope', scopeTitle]));
    buffer.writeln(formatRow(['Total Sessions', sessions.length]));
    if (dateRange != null) {
      buffer.writeln(formatRow(['Date Range', formatDateRange(dateRange)]));
    }
    buffer.writeln();

    buffer.writeln(formatRow([
      'Session ID',
      'Date',
      'Time Slot',
      'Subject',
      'Section',
      'Faculty ID',
      'Total Students',
      'Present',
      'Absent',
      'Late',
      'Excused',
      'Attendance %',
      'Submitted',
      'Locked',
      'Version',
      'Last Modified By',
    ]));

    if (sessions.isEmpty) {
      buffer.writeln(formatRow(['No attendance sessions found', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']));
    } else {
      for (final s in sessions) {
        buffer.writeln(formatRow([
          s.id,
          s.date.toIso8601String().split('T').first,
          s.timeSlot,
          s.subjectName.isNotEmpty ? s.subjectName : s.subjectId,
          s.sectionName.isNotEmpty ? s.sectionName : s.sectionId,
          s.facultyId,
          s.totalStudents,
          s.presentCount,
          s.absentCount,
          s.lateCount,
          s.excusedCount,
          '${s.attendancePercentage.toStringAsFixed(1)}%',
          s.isSubmitted ? 'YES' : 'NO',
          s.isLocked ? 'YES' : 'NO',
          'v${s.version}',
          s.lastModifiedBy ?? (s.createdBy ?? '-'),
        ]));
      }
    }

    return buffer.toString();
  }

  /// Generates a structured PDF/document-formatted text report
  static String generateStructuredPdfReport({
    required AttendanceReportResult reportResult,
  }) {
    final buffer = StringBuffer();
    const divider = '══════════════════════════════════════════════════════════════════════════';
    const subDivider = '──────────────────────────────────────────────────────────────────────────';

    buffer.writeln(divider);
    buffer.writeln('                      ACADEX CAMPUS MANAGEMENT SYSTEM                     ');
    buffer.writeln('                     OFFICIAL ATTENDANCE RECORD REPORT                    ');
    buffer.writeln(divider);
    buffer.writeln();

    buffer.writeln('Report Title  : ${reportResult.title}');
    buffer.writeln('Scope         : ${reportResult.scopeDescription}');
    buffer.writeln('Generated At  : ${reportResult.generatedAt.toIso8601String()}');
    buffer.writeln('Generated By  : ${reportResult.generatedBy}');
    if (reportResult.dateRange != null) {
      buffer.writeln('Period        : ${formatDateRange(reportResult.dateRange)}');
    }
    buffer.writeln('Total Records : ${reportResult.totalRecords}');
    buffer.writeln();

    if (reportResult.summaryStatistics.isNotEmpty) {
      buffer.writeln(subDivider);
      buffer.writeln('                        EXECUTIVE SUMMARY METRICS                         ');
      buffer.writeln(subDivider);
      for (final entry in reportResult.summaryStatistics.entries) {
        final keyPadded = entry.key.padRight(35);
        buffer.writeln('  $keyPadded : ${entry.value}');
      }
      buffer.writeln();
    }

    buffer.writeln(subDivider);
    buffer.writeln('                           DETAILED DATA TABLE                            ');
    buffer.writeln(subDivider);

    // Formatted Table Header
    buffer.writeln(reportResult.headers.map((h) => h.padRight(16)).join(' | '));
    buffer.writeln(subDivider);

    // Formatted Table Rows
    if (reportResult.rows.isEmpty) {
      buffer.writeln('                      -- No matching records found --                     ');
    } else {
      for (final row in reportResult.rows) {
        buffer.writeln(row.map((cell) => cell.toString().padRight(16)).join(' | '));
      }
    }

    buffer.writeln(subDivider);
    buffer.writeln();
    buffer.writeln('Institutional Notice: This document is an official electronic record generated');
    buffer.writeln('by the Acadex Attendance Subsystem. Compliance Threshold = 75.0%.');
    buffer.writeln(divider);

    return buffer.toString();
  }
}
