export enum AcademicCalendarStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',
}

export enum CalendarSourceType {
  MANUAL = 'MANUAL',
  TIMETABLE = 'TIMETABLE',
  ASSIGNMENT = 'ASSIGNMENT',
  PRACTICAL = 'PRACTICAL',
  ASSESSMENT = 'ASSESSMENT',
  ACADEMIC_RESULT = 'ACADEMIC_RESULT',
  OVERRIDE = 'OVERRIDE',
  DERIVED = 'DERIVED',
  SYSTEM = 'SYSTEM',
}

export enum CalendarEventType {
  EVENT = 'EVENT',
  HOLIDAY = 'HOLIDAY',
  PUBLIC_HOLIDAY = 'PUBLIC_HOLIDAY',
  INSTITUTION_HOLIDAY = 'INSTITUTION_HOLIDAY',
  WORKING_DAY = 'WORKING_DAY',
  ACADEMIC_EVENT = 'ACADEMIC_EVENT',
  EXAM = 'EXAM',
  EXAMINATION = 'EXAMINATION',
  INTERNAL_ASSESSMENT = 'INTERNAL_ASSESSMENT',
  PRACTICAL = 'PRACTICAL',
  ASSIGNMENT_DEADLINE = 'ASSIGNMENT_DEADLINE',
  TIMETABLE_CLASS = 'TIMETABLE_CLASS',
  COLLEGE_EVENT = 'COLLEGE_EVENT',
  RESULT_PUBLICATION = 'RESULT_PUBLICATION',
  SEMINAR = 'SEMINAR',
  WORKSHOP = 'WORKSHOP',
  LAB_VIVA = 'LAB_VIVA',
  CLASS_TEST = 'CLASS_TEST',
  DEADLINE = 'DEADLINE',
  OTHER = 'OTHER',
}

export enum CalendarEventScope {
  COLLEGE = 'COLLEGE',
  DEPARTMENT = 'DEPARTMENT',
  COURSE = 'COURSE',
  SEMESTER = 'SEMESTER',
  SECTION = 'SECTION',
  CLASS = 'CLASS',
}

export enum CalendarEventStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  CANCELLED = 'CANCELLED',
  ARCHIVED = 'ARCHIVED',
}

export enum CalendarRecurrence {
  NONE = 'NONE',
  ANNUAL = 'ANNUAL',
  WEEKLY = 'WEEKLY',
}
