export enum NotificationType {
  NOTE_PUBLISHED = 'NOTE_PUBLISHED',
  NOTE_UPDATED = 'NOTE_UPDATED',
  ATTENDANCE_LOW = 'ATTENDANCE_LOW',
  ATTENDANCE_MARKED = 'ATTENDANCE_MARKED',
  ATTENDANCE_ABSENT = 'ATTENDANCE_ABSENT',
  ATTENDANCE_LATE = 'ATTENDANCE_LATE',
  TIMETABLE_PUBLISHED = 'TIMETABLE_PUBLISHED',
  TIMETABLE_UPDATED = 'TIMETABLE_UPDATED',
  TIMETABLE_CANCELLED = 'TIMETABLE_CANCELLED',
  CALENDAR_OVERRIDE = 'CALENDAR_OVERRIDE',
  TEACHER_SUBSTITUTION = 'TEACHER_SUBSTITUTION',
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  SYSTEM = 'SYSTEM',
  // Request Center lifecycle types (Prompt 19)
  REQUEST_RECEIVED = 'REQUEST_RECEIVED',
  REQUEST_UPDATED = 'REQUEST_UPDATED',
  REQUEST_RESPONDED = 'REQUEST_RESPONDED',
  REQUEST_APPROVED = 'REQUEST_APPROVED',
  REQUEST_REJECTED = 'REQUEST_REJECTED',
  // Assignment notification types (Prompt 20)
  ASSIGNMENT_PUBLISHED = 'ASSIGNMENT_PUBLISHED',
  ASSIGNMENT_DUE_SOON = 'ASSIGNMENT_DUE_SOON',
  ASSIGNMENT_OVERDUE = 'ASSIGNMENT_OVERDUE',
  ASSIGNMENT_GRADED = 'ASSIGNMENT_GRADED',
  // Reserved for future prompts
  HOLIDAY = 'HOLIDAY',
  TIMETABLE_CHANGE = 'TIMETABLE_CHANGE',
  ATTENDANCE_ALERT = 'ATTENDANCE_ALERT',
  CALENDAR_EVENT = 'CALENDAR_EVENT',
}

export enum NotificationCategory {
  REQUEST = 'request',
  ASSIGNMENT = 'assignment',
  NOTES = 'notes',
  ATTENDANCE = 'attendance',
  TIMETABLE = 'timetable',
  SYSTEM = 'system',
  ACADEMIC = 'academic',
  ANNOUNCEMENT = 'announcement',
  GENERAL = 'general',
}

export enum NotificationPriority {
  LOW = 'low',
  NORMAL = 'normal',
  HIGH = 'high',
  CRITICAL = 'critical',
}

export enum DevicePlatform {
  ANDROID = 'android',
  IOS = 'ios',
  WEB = 'web',
}

export enum AudienceScope {
  COLLEGE = 'COLLEGE',
  DEPARTMENT = 'DEPARTMENT',
  COURSE = 'COURSE',
  SEMESTER = 'SEMESTER',
  SECTION = 'SECTION',
  ROLE = 'ROLE',
  INDIVIDUAL = 'INDIVIDUAL',
}

export enum AnnouncementStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}
