export enum DateRangePreset {
  TODAY = 'today',
  THIS_WEEK = 'this_week',
  THIS_MONTH = 'this_month',
  CURRENT_SEMESTER = 'current_semester',
  CUSTOM = 'custom',
}

export enum ReportType {
  DASHBOARD = 'DASHBOARD',
  ATTENDANCE_STUDENT = 'ATTENDANCE_STUDENT',
  ATTENDANCE_SECTION = 'ATTENDANCE_SECTION',
  ATTENDANCE_DEPARTMENT = 'ATTENDANCE_DEPARTMENT',
  ATTENDANCE_COLLEGE = 'ATTENDANCE_COLLEGE',
  ATTENDANCE_SUBJECT = 'ATTENDANCE_SUBJECT',
  FACULTY_ACTIVITY = 'FACULTY_ACTIVITY',
  ACADEMIC_HIERARCHY = 'ACADEMIC_HIERARCHY',
  NOTES_CONTENT = 'NOTES_CONTENT',
}

export const ATTENDANCE_THRESHOLDS = {
  LOW_PERCENTAGE_ALERT: 75,
  EXCELLENT_PERCENTAGE: 90,
} as const;
