// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7rVfynfgw65ru7ben6B4-MRQqojH77_Q',
    appId: '1:441884307062:web:92ec8fbfba623dd8bef957',
    messagingSenderId: '441884307062',
    projectId: 'campusmanagement-19ea1',
    authDomain: 'campusmanagement-19ea1.firebaseapp.com',
    storageBucket: 'campusmanagement-19ea1.firebasestorage.app',
    measurementId: 'G-0ZTSJ8VK1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-OzysFXxyF97jgqkGlPgcIjcQ9N1Dqj4',
    appId: '1:441884307062:android:cfc95d77367dee33bef957',
    messagingSenderId: '441884307062',
    projectId: 'campusmanagement-19ea1',
    storageBucket: 'campusmanagement-19ea1.firebasestorage.app',
  );
}
